// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Badge is the predicate function for badge builders.
type Badge func(*sql.Selector)

// Challenge is the predicate function for challenge builders.
type Challenge func(*sql.Selector)

// Prediction is the predicate function for prediction builders.
type Prediction func(*sql.Selector)

// Proof is the predicate function for proof builders.
type Proof func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserSession is the predicate function for usersession builders.
type UserSession func(*sql.Selector)
