version: '3.7'

services:
  predictor_db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: test
      POSTGRES_DB: predictor
    volumes:
      - predictor-database-data:/var/lib/postgresql/data/
    ports:
      - "6432:5432"

volumes:
  predictor-database-data: